= Eve-PS README

== Introduction

This is just a bunch of PowerShell cmdlets that interface with https://esi.evetech.net/ui/#/[Eve's ESI].

== License

See xref:COPYING.adoc[] for the primary terms of copying for this repository.

== Dependencies

Requires https://github.com/RamblingCookieMonster/PSSQLite[PSSQLite] and https://github.com/proxb/PoshRSJob[PoshRSJob].

== Getting Started

Overall steps:

.  Add an application on the https://developers.eveonline.com/[Eve Developers portal]
.. Give a good name (such as Eve-PS)
.. A short description (such as "Access ESI via PowerShell")
.. Set Connection Type to Authentication & API Access with the scope "esi-universe.read_structures.v1" (needed to read market orders inside structures you can dock with).
.. Set the callback URL to "++http://localhost:64782/++"
.. Click Create Application
. Open your application settings in the EVE Developers portal
. Copy secrets.example.ps1 to secrets.ps1
. In secrets.ps1, set $global:EsiClientId to your Client ID

After that, you should be A-OK to run the commands.

To login, run `Invoke-EsiLogin`.

== Known issues

For some reason, tab and menu completion in PowerShell stops working if anything uses PoshRSJob is run more than a couple of times.

== Other tries

I tried using https://github.com/Azure/autorest[AutoRest], but it had compile issues after generating from the https://esi.evetech.net/latest/swagger.json[swagger file].

I also attempted to use the swagger directly to write out PowerShell cmdlets, but I have a feeling I need to go through a few manual endpoint adds before I get the flow of the format.  Would reduce a lot of labor, though, and I am having too much fun hand-writing it all.

I could also probably use the ESI.NET library, but it's fun writing the code.

== Other notes

This is currently under a rewrite because PowerShell is just too slow.  I am sure there are ways to speed it up, but threading in PowerShell is still going to be a frustrating chore.

Look in the EveCore directory for the C# rewrite.  It is planned to expose the functionality in cmdlets still, just with C# on the backend.
